#!/usr/bin/env python3
##
## GOOGLE KICK START, 2020
## ROUND H
#!

j = int(input())
for i in range(1, j + 1):
    end = 0
    min, max = map(int, input().split(" "))
    while(min <= max):
        test = 0
        for k in range(0, len(str(min))):
            if(k % 2 == 0 and int(str(min)[k]) % 2 != 0):
                test = 1
                break
            elif(k % 2 != 0 and int(str(min)[k]) % 2 == 0):
                test = 1
                break
        if (test == 0):
            end += 1
        min += 1
    print("case #" + "%.0f" % i + ":", end)
    