#!/usr/bin/env python3
##
## GOOGLE KICK START, 2020
## ROUND H
#!

j = int(input())
for i in range(1, j + 1):
    max_l, cur_l, sword = map(int, input().split(" "))
    max_l2, cur_l2, sword2 = max_l, cur_l, sword
    cur_t = cur_l
    nb_l = 0
    nb_l = cur_l - sword
    cur_l = sword
    nb_l += max_l - cur_l + cur_t
#method 2
    nb2_l = cur_l2 + max_l2

    if nb_l > nb2_l:
        end = nb2_l
    else:
        end = nb_l
    print("case #" + "%.0f" % i + ":", end)
    